export class RouterService {
  /**
   * Main handler that routes the message to the appropriate service.
   * Now calls the centralized /api/chat endpoint on the server.
   */
  public async handle(message: string): Promise<{ type: string; content: any }> {
    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message })
      });
      const data = await response.json();
      
      if (data.error) throw new Error(data.error);
      
      // Determine type based on content prefix or server response
      let type = "chat";
      if (data.reply.includes("[Ollama]") || data.reply.includes("[EXECUTION BY GEMMA]")) type = "ollama";
      else if (data.reply.includes("[GPT-4]")) type = "gpt4";
      else if (data.reply.includes("[PLAN GENERATED BY GPT-4]")) type = "plan";
      else if (data.reply.includes("تم تنظيف") || data.reply.includes("تم فحص") || data.reply.includes("جارِ تحليل")) type = "maintenance";
      
      return { type, content: data.reply };
    } catch (error: any) {
      console.error("Chat API failed:", error);
      return { type: "error", content: error.message || "فشل الاتصال بنواة النظام الموحدة." };
    }
  }
}

export const routerService = new RouterService();
